spring:
  config:
    import: optional:secrets.yml
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: <clientID>
#            client-secret: <clientSecret>